### PR TITLE
Stronger security with a unified cdn and waf

### PR DESCRIPTION
**Pull request by BrooksCunningham**
The goal is to incorporate the guidance in the following blog into this repository.

https://www.fastly.com/blog/stronger-security-with-a-unified-cdn-and-waf

### CODE REVIEW

**Review by gndooz — APPROVED** [review]
Looks good!

**Review by gndooz — APPROVED** [review]
approved!

**Review by dmichael-fastly — APPROVED** [review]
Rad!

**Review by gndooz — APPROVED** [review]

**Review by gndooz — APPROVED** [review]
all good

**Pull request merged**
